// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtHFQsDrdfLrQSXBL1J_Vv8XuX1_2PFA8',
    appId: '1:887751240825:web:8710cf6fd1b33d3f0338a8',
    messagingSenderId: '887751240825',
    projectId: 'firebseproject-483b1',
    authDomain: 'firebseproject-483b1.firebaseapp.com',
    databaseURL: 'https://firebseproject-483b1-default-rtdb.firebaseio.com',
    storageBucket: 'firebseproject-483b1.appspot.com',
    measurementId: 'G-YK4GK70LXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-H0kosTyWL9LhHrm9dL88_LWPjzS_7h8',
    appId: '1:887751240825:android:a7e89828c740d7e50338a8',
    messagingSenderId: '887751240825',
    projectId: 'firebseproject-483b1',
    databaseURL: 'https://firebseproject-483b1-default-rtdb.firebaseio.com',
    storageBucket: 'firebseproject-483b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjkDFCTMjxjFL-0KaYm6fxoIqaDPiIVhw',
    appId: '1:887751240825:ios:46f10b33359345440338a8',
    messagingSenderId: '887751240825',
    projectId: 'firebseproject-483b1',
    databaseURL: 'https://firebseproject-483b1-default-rtdb.firebaseio.com',
    storageBucket: 'firebseproject-483b1.appspot.com',
    iosClientId: '887751240825-m3lupkdpqbgd5poksnoe42ffec5pg39f.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebseauthentication',
  );
}
